$(document).ready(

  function(){
 
    $('#imgCT1').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT1.png');
      }
    );

    $('#imgCT2').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT2.png');
      }
    );

    $('#imgCT3').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT3.png');
      }
    );

    $('#imgCT4').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT4.png');
      }
    );

    $('#imgCT5').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT5.png');
      }
    );

    $('#imgCT6').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT6.png');
      }
    );
    $('#imgCT7').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT7.png');
      }
    );
    $('#imgCT8').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT8.png');
      }
    );
    $('#imgCT9').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT9.png');
      }
    );
    $('#imgCT10').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT10.png');
      }
    );
    $('#imgCT11').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT11.png');
      }
    );
    $('#imgCT12').click(
      function()
      {
        $('#cambia').attr('src','img/imgCT12.png');
      }
    );
  //cambia TV
      $('#imgTV1').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV1.png');
      }
    );

    $('#imgTV2').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV2.png');
      }
    );

    $('#imgTV3').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV3.png');
      }
    );

    $('#imgTV4').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV4.png');
      }
    );

    $('#imgTV5').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV5.png');
      }
    );

    $('#imgTV6').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV6.png');
      }
    );
    $('#imgTV7').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV7.png');
      }
    );
    $('#imgTV8').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV8.png');
      }
    );
    $('#imgTV9').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV9.png');
      }
    );
    $('#imgTV10').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV10.png');
      }
    );
    $('#imgTV11').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV11.png');
      }
    );
    $('#imgTV12').click(
      function()
      {
        $('#cambia1').attr('src','img/imgTV12.png');
      }
    );
    //cambia compu
    $('#imgC1').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC1.png');
      }
    );

    $('#imgC2').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC2.png');
      }
    );

    $('#imgC3').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC3.png');
      }
    );

    $('#imgC4').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC4.png');
      }
    );

    $('#imgC5').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC5.png');
      }
    );

    $('#imgC6').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC6.png');
      }
    );
    $('#imgC7').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC7.png');
      }
    );
    $('#imgC8').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC8.png');
      }
    );
    $('#imgC9').click(
      function()
      {
        $('#cambia2').attr('src','img/imgC9.png');
      }
    );
    //cambia tablets
      $('#imgT1').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT1.png');
      }
    );

    $('#imgT2').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT2.png');
      }
    );

    $('#imgT3').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT3.png');
      }
    );

    $('#imgT4').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT4.png');
      }
    );

    $('#imgT5').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT5.png');
      }
    );

    $('#imgT6').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT6.png');
      }
    );
    $('#imgT7').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT7.png');
      }
    );
    $('#imgT8').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT8.png');
      }
    );
    $('#imgT9').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT9.png');
      }
    );
    $('#imgT10').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT10.png');
      }
    );
    $('#imgT11').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT11.png');
      }
    );
    $('#imgT12').click(
      function()
      {
        $('#cambiaT').attr('src','img/imgT12.png');
      }
    );
    //cambia camaras
    $('#imgF1').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF1.png');
      }
    );

    $('#imgF2').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF2.png');
      }
    );

    $('#imgF3').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF3.png');
      }
    );

    $('#imgF4').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF4.png');
      }
    );

    $('#imgF5').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF5.png');
      }
    );

    $('#imgF6').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF6.png');
      }
    );
    $('#imgF7').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF7.png');
      }
    );
    $('#imgF8').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF8.png');
      }
    );
    $('#imgF9').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF9.png');
      }
    );
    $('#imgF10').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF10.png');
      }
    );
    $('#imgF11').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF11.png');
      }
    );
    $('#imgF12').click(
      function()
      {
        $('#cambia1').attr('src','img/imgF12.png');
      }
    );
    //cambia Videojuegod
          $('#imgV1').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV.png');
      }
    );

    $('#imgV2').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV2.png');
      }
    );

    $('#imgV3').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV3.png');
      }
    );

    $('#imgV4').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV4.png');
      }
    );

    $('#imgV5').click(
      function()
      {
        $('#cambia1').attr('src','img/imgV5.png');
      }
    );

    $('#imgV6').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV6.png');
      }
    );
    $('#imgV7').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV7.png');
      }
    );
    $('#imgV8').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV8.png');
      }
    );
    $('#imgV9').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV9.png');
      }
    );
    $('#imgV10').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV10.png');
      }
    );
    $('#imgV11').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV11.png');
      }
    );
    $('#imgV12').click(
      function()
      {
        $('#cambiaV').attr('src','img/imgV12.png');
      }
    );
    //cambia consolas
    $('#imgVC1').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC1.png');
      }
    );

    $('#imgVC2').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC2.png');
      }
    );

    $('#imgVC3').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC3.png');
      }
    );

    $('#imgVC4').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC4.png');
      }
    );

    $('#imgVC5').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC5.png');
      }
    );

    $('#imgVC6').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC6.png');
      }
    );
    $('#imgVC7').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC7.png');
      }
    );
    $('#imgVC8').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC8.png');
      }
    );
    $('#imgVC9').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC9.png');
      }
    );
    $('#imgVC10').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC10.png');
      }
    );
    $('#imgVC11').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC11.png');
      }
    );
    $('#imgVC12').click(
      function()
      {
        $('#cambiaVC').attr('src','img/imgVC12.png');
      }
    );
    //cambia audio
        $('#imgA1').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA1.png');
      }
    );

    $('#imgA2').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA2.png');
      }
    );

    $('#imgA3').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA3.png');
      }
    );

    $('#imgA4').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA4.png');
      }
    );

    $('#imgA5').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA5.png');
      }
    );

    $('#imgA6').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA6.png');
      }
    );
    $('#imgA7').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA7.png');
      }
    );
    $('#imgA8').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA8.png');
      }
    );
    $('#imgA9').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA9.png');
      }
    );
    $('#imgA10').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA10.png');
      }
    );
    $('#imgA11').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA11.png');
      }
    );
    $('#imgA12').click(
      function()
      {
        $('#cambiaA').attr('src','img/imgA12.png');
      }
    );
    //cambia fotografia
        $('#imgF1').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF1.png');
      }
    );

    $('#imgF2').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF2.png');
      }
    );

    $('#imgF3').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF3.png');
      }
    );

    $('#imgF4').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF4.png');
      }
    );

    $('#imgF5').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF5.png');
      }
    );

    $('#imgF6').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF6.png');
      }
    );
    $('#imgF7').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF7.png');
      }
    );
    $('#imgF8').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF8.png');
      }
    );
    $('#imgF9').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF9.png');
      }
    );
    $('#imgF10').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF10.png');
      }
    );
    $('#imgF11').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF11.png');
      }
    );
    $('#imgF12').click(
      function()
      {
        $('#cambiaF').attr('src','img/imgF12.png');
      }
    );
  }

);