$(document).ready(

  function(){
 
    $('#imgCT1').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT1.png');
      }
    );

    $('#imgCT2').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT2.png');
      }
    );

    $('#imgCT3').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT3.png');
      }
    );

    $('#imgCT4').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT4.png');
      }
    );

    $('#imgCT5').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT5.png');
      }
    );

    $('#imgCT6').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT6.png');
      }
    );
    $('#imgCT7').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT7.png');
      }
    );
    $('#imgCT8').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT8.png');
      }
    );
    $('#imgCT9').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT9.png');
      }
    );
    $('#imgCT10').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT10.png');
      }
    );
    $('#imgCT11').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT11.png');
      }
    );
    $('#imgCT12').click(
      function()
      {
        $('#cambia').attr('src','imagenes/imgCT12.png');
      }
    );
  //cambia TV
      $('#imgTV1').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV1.png');
      }
    );

    $('#imgTV2').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV2.png');
      }
    );

    $('#imgTV3').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV3.png');
      }
    );

    $('#imgTV4').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV4.png');
      }
    );

    $('#imgTV5').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV5.png');
      }
    );

    $('#imgTV6').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV6.png');
      }
    );
    $('#imgTV7').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV7.png');
      }
    );
    $('#imgTV8').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV8.png');
      }
    );
    $('#imgTV9').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV9.png');
      }
    );
    $('#imgTV10').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV10.png');
      }
    );
    $('#imgTV11').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV11.png');
      }
    );
    $('#imgTV12').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgTV12.png');
      }
    );
    //cambia compu
    $('#imgC1').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC1.png');
      }
    );

    $('#imgC2').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC2.png');
      }
    );

    $('#imgC3').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC3.png');
      }
    );

    $('#imgC4').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC4.png');
      }
    );

    $('#imgC5').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC5.png');
      }
    );

    $('#imgC6').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC6.png');
      }
    );
    $('#imgC7').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC7.png');
      }
    );
    $('#imgC8').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC8.png');
      }
    );
    $('#imgC9').click(
      function()
      {
        $('#cambia2').attr('src','imagenes/imgC9.png');
      }
    );
    //cambia tablets
      $('#imgT1').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT1.png');
      }
    );

    $('#imgT2').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT2.png');
      }
    );

    $('#imgT3').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT3.png');
      }
    );

    $('#imgT4').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT4.png');
      }
    );

    $('#imgT5').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT5.png');
      }
    );

    $('#imgT6').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT6.png');
      }
    );
    $('#imgT7').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT7.png');
      }
    );
    $('#imgT8').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT8.png');
      }
    );
    $('#imgT9').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT9.png');
      }
    );
    $('#imgT10').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT10.png');
      }
    );
    $('#imgT11').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT11.png');
      }
    );
    $('#imgT12').click(
      function()
      {
        $('#cambiaT').attr('src','imagenes/imgT12.png');
      }
    );
    //cambia camaras
    $('#imgF1').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF1.png');
      }
    );

    $('#imgF2').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF2.png');
      }
    );

    $('#imgF3').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF3.png');
      }
    );

    $('#imgF4').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF4.png');
      }
    );

    $('#imgF5').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF5.png');
      }
    );

    $('#imgF6').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF6.png');
      }
    );
    $('#imgF7').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF7.png');
      }
    );
    $('#imgF8').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF8.png');
      }
    );
    $('#imgF9').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF9.png');
      }
    );
    $('#imgF10').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF10.png');
      }
    );
    $('#imgF11').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF11.png');
      }
    );
    $('#imgF12').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgF12.png');
      }
    );
    //cambia Videojuegod
          $('#imgV1').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV.png');
      }
    );

    $('#imgV2').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV2.png');
      }
    );

    $('#imgV3').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV3.png');
      }
    );

    $('#imgV4').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV4.png');
      }
    );

    $('#imgV5').click(
      function()
      {
        $('#cambia1').attr('src','imagenes/imgV5.png');
      }
    );

    $('#imgV6').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV6.png');
      }
    );
    $('#imgV7').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV7.png');
      }
    );
    $('#imgV8').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV8.png');
      }
    );
    $('#imgV9').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV9.png');
      }
    );
    $('#imgV10').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV10.png');
      }
    );
    $('#imgV11').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV11.png');
      }
    );
    $('#imgV12').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgV12.png');
      }
    );
    //cambia consolas
    $('#imgVC1').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC1.png');
      }
    );

    $('#imgVC2').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC2.png');
      }
    );

    $('#imgVC3').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC3.png');
      }
    );

    $('#imgVC4').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC4.png');
      }
    );

    $('#imgVC5').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC5.png');
      }
    );

    $('#imgVC6').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC6.png');
      }
    );
    $('#imgVC7').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC7.png');
      }
    );
    $('#imgVC8').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC8.png');
      }
    );
    $('#imgVC9').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC9.png');
      }
    );
    $('#imgVC10').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC10.png');
      }
    );
    $('#imgVC11').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC11.png');
      }
    );
    $('#imgVC12').click(
      function()
      {
        $('#cambiaV').attr('src','imagenes/imgVC12.png');
      }
    );
    //cambia audio
        $('#imgA1').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA1.png');
      }
    );

    $('#imgA2').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA2.png');
      }
    );

    $('#imgA3').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA3.png');
      }
    );

    $('#imgA4').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA4.png');
      }
    );

    $('#imgA5').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA5.png');
      }
    );

    $('#imgA6').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA6.png');
      }
    );
    $('#imgA7').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA7.png');
      }
    );
    $('#imgA8').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA8.png');
      }
    );
    $('#imgA9').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA9.png');
      }
    );
    $('#imgA10').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA10.png');
      }
    );
    $('#imgA11').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA11.png');
      }
    );
    $('#imgA12').click(
      function()
      {
        $('#cambiaA').attr('src','imagenes/imgA12.png');
      }
    );
    //cambia fotografia
        $('#imgF1').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF1.png');
      }
    );

    $('#imgF2').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF2.png');
      }
    );

    $('#imgF3').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF3.png');
      }
    );

    $('#imgF4').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF4.png');
      }
    );

    $('#imgF5').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF5.png');
      }
    );

    $('#imgF6').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF6.png');
      }
    );
    $('#imgF7').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF7.png');
      }
    );
    $('#imgF8').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF8.png');
      }
    );
    $('#imgF9').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF9.png');
      }
    );
    $('#imgF10').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF10.png');
      }
    );
    $('#imgF11').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF11.png');
      }
    );
    $('#imgF12').click(
      function()
      {
        $('#cambiaF').attr('src','imagenes/imgF12.png');
      }
    );
  }
);